# Generated by Django 5.2 on 2026-01-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='process_at',
            new_name='processed_at',
        ),
    ]
